In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [5]:
os.getcwd()

'C:\\Users\\HP'

In [6]:
os.chdir('E:\\Simpli Learn Project Dataset\\CSV of different datasets')

In [126]:
df=pd.read_csv('loan.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0    Loan ID           614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
 13  Unnamed: 13        0 non-null      float64
dtypes: float64(5), int64(1), object(8)
memory usage: 67.3+ KB


In [130]:
df.isnull().sum()

 Loan ID               0
Gender                 0
Married                0
Dependents             0
Education              0
Self_Employed          0
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount             0
Loan_Amount_Term       0
Credit_History         0
Property_Area          0
Loan_Status            0
Unnamed: 13          614
dtype: int64

In [129]:
#Dealing with Null values
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)
df['Married'].fillna(df['Married'].mode()[0],inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0],inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0],inplace=True)
df['LoanAmount'].fillna(df['LoanAmount'].mean(),inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean(),inplace=True)
df['Credit_History'].fillna(df['Credit_History'].mean(),inplace=True)

In [115]:
df.head()

Loan ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  Unnamed: 13  
0             1.0         Urban           Y          NaN  
1             1.0         Rural           N          NaN  
2             1.0         Urban           Y          NaN  
3             1.0         Urban           Y          NaN  
4             1.0         Urban           Y          NaN

In [131]:
#Dropping unwanted column
df.drop('Unnamed: 13',axis=1,inplace=True)

In [134]:
#check each column catgorical having how many vaues and map accordingly
df['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [135]:
#Dealing with categorical variable
df['Gender']=df['Gender'].map({'Male':1,'Female':0})
df['Married']=df['Married'].map({'Yes':1,'No':0})
df['Education']=df['Education'].map({'Graduate':1,'Not Graduate':0})
df['Self_Employed']=df['Self_Employed'].map({'Yes':1,'No':0})
df['Property_Area']=df['Property_Area'].map({'Urban':1,'Rural':0,'Semiurban':2})
df['Loan_Status']=df['Loan_Status'].map({'Y':1,'N':0})

In [132]:
#changing value '3+' in Dependents column to 4
df['Dependents'].replace(to_replace='3+',value='4')

0      0
1      1
2      0
3      0
4      0
      ..
609    0
610    4
611    1
612    2
613    0
Name: Dependents, Length: 614, dtype: object

In [136]:
df.head()

Loan ID  Gender  Married Dependents  Education  Self_Employed  \
0  LP001002       1        0          0          1              0   
1  LP001003       1        1          1          1              0   
2  LP001005       1        1          0          1              1   
3  LP001006       1        1          0          0              0   
4  LP001008       1        0          0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              1            1  
1             1.0              0            0  
2             1.0              1            1  
3             1.0              1            1  
4             1.0              1            1

In [140]:
#Making X and Y vaiable
x=df[['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area']]
y=df['Loan_Status']

In [143]:
x.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          1              0         0.072991   
1       1        1          1          1              0        -0.134412   
2       1        1          0          1              1        -0.393747   
3       1        1          0          0              0        -0.462062   
4       1        0          0          1              0         0.097728   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0          -0.554487    0.000000          0.279851             1.0   
1          -0.038732   -0.219273          0.279851             1.0   
2          -0.554487   -0.957641          0.279851             1.0   
3           0.251980   -0.314547          0.279851             1.0   
4          -0.554487   -0.064454          0.279851             1.0   

   Property_Area  
0              1  
1              0  
2              1  
3              1  
4              1

In [142]:
#Feature scaling to make values of different columns in range
col=['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x[col]=st.fit_transform(x[col])

C:\Users\HP\AppData\Local\Temp\ipykernel_8844\1670877899.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[col]=st.fit_transform(x[col])


In [152]:
x.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          1              0         0.072991   
1       1        1          1          1              0        -0.134412   
2       1        1          0          1              1        -0.393747   
3       1        1          0          0              0        -0.462062   
4       1        0          0          1              0         0.097728   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0          -0.554487    0.000000          0.279851             1.0   
1          -0.038732   -0.219273          0.279851             1.0   
2          -0.554487   -0.957641          0.279851             1.0   
3           0.251980   -0.314547          0.279851             1.0   
4          -0.554487   -0.064454          0.279851             1.0   

   Property_Area  
0              1  
1              0  
2              1  
3              1  
4              1

In [163]:
x['Dependents']=x['Dependents'].replace(to_replace='3+',value='4')
x.tail()

C:\Users\HP\AppData\Local\Temp\ipykernel_8844\3720373783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Dependents']=x['Dependents'].replace(to_replace='3+',value='4')


Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
609       0        0          0          1              0        -0.410130   
610       1        1          4          1              0        -0.212557   
611       1        1          1          1              0         0.437174   
612       1        1          2          1              0         0.357064   
613       0        0          0          1              1        -0.134412   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
609          -0.554487   -0.898095          0.279851             1.0   
610          -0.554487   -1.267279         -2.518655             1.0   
611          -0.472404    1.269371          0.279851             1.0   
612          -0.554487    0.483367          0.279851             1.0   
613          -0.554487   -0.159728          0.279851             0.0   

     Property_Area  
609              0  
610              0  
611              1  
612              1  
613              2

In [172]:
#splitting dataset into train and test and aplying k fold validation
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [189]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

In [194]:
#Linear Regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [191]:
y_test.unique()

array([0, 1], dtype=int64)

In [196]:
y_pred=np.where(y_pred>0.5,1,0)

In [197]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [198]:
accuracy_score(y_test,y_pred)

0.8252032520325203

In [199]:
#Decision Tree 
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [200]:
y_pred

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0], dtype=int64)

In [201]:
accuracy_score(y_test,y_pred)

0.6910569105691057

In [210]:
from sklearn.ensemble import RandomForestClassifier
dt=RandomForestClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [211]:
accuracy_score(y_test,y_pred)

0.8048780487804879

In [212]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
dt=GaussianNB()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [213]:
accuracy_score(y_test,y_pred)

0.8170731707317073

In [ ]:
#THATS ALL BEGINNER . KEEP CONECTED TO LEARN AND GROW MORE 